In [1]:
import pandas as pd

In [2]:
fts_21 = pd.read_csv('../../data/raw/fantasy/21.csv')
fts_22 = pd.read_csv('../../data/raw/fantasy/22.csv')
fts_23 = pd.read_csv('../../data/raw/fantasy/23.csv')
fts_24 = pd.read_csv('../../data/raw/fantasy/24.csv')

In [3]:
team_encode = pd.read_csv('../../data/raw/fantasy/team_encode.csv')
team_encode = team_encode[team_encode['season'].isin(['2020-21', '2021-22', '2022-23', '2023-24'])]

In [4]:
team_encode_21 = team_encode[team_encode['season']=='2020-21'][['team', 'team_name']].set_index('team').to_dict()['team_name']
team_encode_22 = team_encode[team_encode['season']=='2021-22'][['team', 'team_name']].set_index('team').to_dict()['team_name']
team_encode_23 = team_encode[team_encode['season']=='2022-23'][['team', 'team_name']].set_index('team').to_dict()['team_name']
team_encode_24 = team_encode[team_encode['season']=='2023-24'][['team', 'team_name']].set_index('team').to_dict()['team_name']

In [5]:
team_encode_21

{1: 'Arsenal',
 2: 'Aston Villa',
 3: 'Brighton',
 4: 'Burnley',
 5: 'Chelsea',
 6: 'Crystal Palace',
 7: 'Everton',
 8: 'Fulham',
 9: 'Leicester',
 10: 'Leeds',
 11: 'Liverpool',
 12: 'Man City',
 13: 'Man Utd',
 14: 'Newcastle',
 15: 'Sheffield Utd',
 16: 'Southampton',
 17: 'Spurs',
 18: 'West Brom',
 19: 'West Ham',
 20: 'Wolves'}

In [6]:
fts_21['opponent_team'] = fts_21['opponent_team'].apply(lambda x: team_encode_21[x])
fts_22['opponent_team'] = fts_22['opponent_team'].apply(lambda x: team_encode_22[x])
fts_23['opponent_team'] = fts_23['opponent_team'].apply(lambda x: team_encode_23[x])
fts_24['opponent_team'] = fts_24['opponent_team'].apply(lambda x: team_encode_24[x])

In [7]:
fts_21['season'] = '2020-2021'
fts_22['season'] = '2021-2022'
fts_23['season'] = '2022-2023'
fts_24['season'] = '2023-2024'

In [8]:
fts_21.columns

Index(['name', 'position', 'team', 'xP', 'assists', 'bonus', 'bps',
       'clean_sheets', 'creativity', 'element', 'fixture', 'goals_conceded',
       'goals_scored', 'ict_index', 'influence', 'kickoff_time', 'minutes',
       'opponent_team', 'own_goals', 'penalties_missed', 'penalties_saved',
       'red_cards', 'round', 'saves', 'selected', 'team_a_score',
       'team_h_score', 'threat', 'total_points', 'transfers_balance',
       'transfers_in', 'transfers_out', 'value', 'was_home', 'yellow_cards',
       'GW', 'season'],
      dtype='object')

In [9]:
"""
features for layer 2:
    total_points, bonus, value, creativity, influence, threat, selected, transfers_balance

create "time_played": 1 if "minutes" > 45 else 0

create 4 df: home_1, away_1, home_0, away_0
"""

'\nfeatures for layer 2:\n    total_points, bonus, value, creativity, influence, threat, selected, transfers_balance\n\ncreate "time_played": 1 if "minutes" > 45 else 0\n\ncreate 4 df: home_1, away_1, home_0, away_0\n'

In [10]:
fts_21 = fts_21[['name', 'team', 'GW', 'season', 'total_points', 'bonus', 'value', 'creativity', 'influence', 'threat', 'selected', 'transfers_balance', 
                'minutes', 'kickoff_time', 'was_home','opponent_team']]
fts_22 = fts_22[['name', 'team', 'GW', 'season', 'total_points', 'bonus', 'value', 'creativity', 'influence', 'threat', 'selected', 'transfers_balance', 
                'minutes', 'kickoff_time', 'was_home','opponent_team']]
fts_23 = fts_23[['name', 'team', 'GW', 'season', 'total_points', 'bonus', 'value', 'creativity', 'influence', 'threat', 'selected', 'transfers_balance', 
                'minutes', 'kickoff_time', 'was_home','opponent_team']]
fts_24 = fts_24[['name', 'team', 'GW', 'season', 'total_points', 'bonus', 'value', 'creativity', 'influence', 'threat', 'selected', 'transfers_balance', 
                'minutes', 'kickoff_time', 'was_home','opponent_team']]

In [11]:
fts = pd.concat([fts_21, fts_22, fts_23, fts_24])
fts.head()

,name,team,GW,season,total_points,bonus,value,creativity,influence,threat,selected,transfers_balance,minutes,kickoff_time,was_home,opponent_team
0,Aaron Connolly,Brighton,1,2020-2021,1,0,55,0.3,1.2,32.0,32205,0,45,2020-09-14T19:15:00Z,True,Chelsea
1,Aaron Cresswell,West Ham,1,2020-2021,1,0,50,11.2,10.4,0.0,70232,0,90,2020-09-12T19:00:00Z,True,Newcastle
2,Aaron Mooy,Brighton,1,2020-2021,0,0,50,0.0,0.0,0.0,2010,0,0,2020-09-14T19:15:00Z,True,Chelsea
3,Aaron Ramsdale,Sheffield Utd,1,2020-2021,1,0,50,0.0,18.2,0.0,462939,0,90,2020-09-14T17:00:00Z,True,Wolves
4,Abdoulaye Doucour√©,Everton,1,2020-2021,3,0,55,44.6,20.4,4.0,143040,0,90,2020-09-13T15:30:00Z,False,Spurs

In [12]:
len(fts)

106042

In [13]:
fts.isnull().sum()

name                 0
team                 0
GW                   0
season               0
total_points         0
bonus                0
value                0
creativity           0
influence            0
threat               0
selected             0
transfers_balance    0
minutes              0
kickoff_time         0
was_home             0
opponent_team        0
dtype: int64

In [14]:
name_map = {
    'adama traore diarra': 'adama traore',
    'ademipo odubeko': 'mipo odubeko',
    'adrian san miguel del castillo': 'adrian',
    'ahmed el mohamady': 'ahmed elmohamady',
    'ahmed el-sayed hegazy': 'ahmed hegazy',
    'ajibola alese': 'aji alese',
    'albert sambi lokonga': 'albert lokonga',
    'alejandro garnacho ferreyra': 'alejandro garnacho',
    'alex mighten': 'Alexander Mighten',
    'alex moreno lopera': 'alex moreno',
    'alex nicolao telles': 'Alex Telles',
    'alexandre moreno lopera': 'alex moreno',
    'ali al-hamadi': 'Ali Al Hamadi',
    'alisson ramses becker': 'Alisson Becker',
    'allan marques loureiro': 'allan',
    'alvaro fernandez carreras': '√Ålvaro Fern√°ndez',
    'andre filipe tavares gomes': 'Andr√© Gomes',
    'andre tavares gomes': 'Andr√© Gomes',
    'andre trindade da costa neto': 'Andr√©',
    'andre-frank zambo anguissa': 'Frank Anguissa',
    'andreas hoelgebaum pereira': 'Andreas Pereira',
    'andrew robertson': 'Andy Robertson',
    'andrey nascimento dos santos': 'Andrey Santos',
    'andriy yarmolenko': 'Andrey Yarmolenko',
    'anis slimane': 'Anis Ben Slimane',
    'anssumane fati vieira': 'Ansu Fati',
    'antony matheus dos santos': 'antony',
    'arijanet muric': 'Aro Muriƒá',
    'arnaut danjuma groeneveld': 'Arnaut Danjuma',
    'arthur henrique ramos de oliveira melo': 'Arthur Melo',
    'ayotomiwa dele-bashiru': 'Tom Dele-Bashiru',
    'bamidele alli': 'dele alli',
    'ben brereton diaz': 'Ben Brereton',
    'benicio baker-boaitey': 'Benicio Boaitey',
    'benjamin chilwell': 'Ben Chilwell',
    'benjamin chrisene': 'Ben Chrisene',
    'benjamin white': 'Ben White',
    'bernard anicio caldeira duarte': 'Bernard',
    'bernardo fernandes da silva junior': 'Bernardo',
    'bernardo mota veiga de carvalho e silva': 'Bernardo Silva',
    'bernardo veiga de carvalho e silva': 'Bernardo Silva',
    'bobby decordova-reid': 'Bobby De Cordova-Reid',
    'boubacar traore': 'Boubacar Traor√© II',
    'brandon aguilera zamora': 'Brandon Aguilera',
    'brandon pierrick': 'Brandon Pierrick',
    'bruno andre cavaco jordao': 'Bruno Jord√£o',
    'bruno guimaraes rodriguez moura': 'Bruno Guimar√£es',
    'bruno miguel borges fernandes': 'Bruno Fernandes',
    'bryan gil salvatierra': 'Bryan Gil',
    'callum scanlon': 'Calum Scanlon',
    'carlos alcaraz duran': 'Carlos Alcaraz',
    'carlos henrique casimiro': 'Casemiro',
    'carlos miguel dos santos pereira': 'Carlos Miguel',
    'carlos roberto forbs borges': 'Carlos Forbs',
    'carlos vinicius alves morais': 'Carlos Vin√≠cius',
    'cedric alves soares': 'C√©dric',
    'cedric soares': 'C√©dric',
    'cesar azpilicueta': 'Azpilicueta',
    'chadi riad dnanou': 'Chadi Riad',
    'christian atsu': 'Christian Atsu',
    'claudio bravo': 'Claudio Bravo',
    'conrad egan-riley': 'CJ Egan-Riley',
    'cristiano ronaldo dos santos aveiro': 'Cristiano Ronaldo',
    'daniel castelo podence': 'Daniel Podence',
    'daniel ceballos fernandez': 'Dani Ceballos',
    'daniel james': 'Dan James',
    "daniel n'lundulu": "Dan N'Lundulu",
    'danilo dos santos de oliveira': 'Danilo',
    'darwin nunez ribeiro': 'Darwin N√∫√±ez',
    'david datro fofana': 'David Fofana',
    'david de gea': 'De Gea',
    'david de gea quintana': 'De Gea',
    'david luiz moreira marinho': 'David Luiz',
    'david raya martin': 'David Raya',
    'deivid washington de souza eugenio': 'Deivid Washington',
    'detlef esapa osong': 'Detlef Osong',
    'diego carlos santos silva': 'Diego Carlos',
    'diego da silva costa': 'Diego Costa',
    'diego llorente': 'Llorente',
    'diego manuel jadon da silva moreira': 'Diego Moreira',
    'diogo dalot teixeira': 'Diogo Dalot',
    'diogo pinheiro monteiro': 'Diogo Monteiro',
    'diogo teixeira da silva': 'Diogo Jota',
    'djordje petrovic': 'ƒêorƒëe Petroviƒá',
    'domingos quina': 'Domingos Quina',
    'dominic ballard': 'Dom Ballard',
    'dominic dos santos martins': 'Dominic Martins',
    'dominic solanke-mitchell': 'Dominic Solanke',
    'douglas luiz soares de paulo': 'Douglas Luiz',
    'ederson santana de moraes': 'Ederson',
    'edson alvarez velazquez': 'Edson √Ålvarez',
    'edward nketiah': 'Eddie Nketiah',
    'elliot thorpe': 'Harvey Elliott',
    'emerson aparecido leite de souza junior': 'Emerson Royal',
    'emerson leite de souza junior': 'Emerson Royal',
    'emerson palmieri dos santos': 'Emerson',
    'emiliano buendia stati': 'Emiliano Buendia',
    'emiliano martinez romero': 'Emiliano Mart√≠nez',
    'endo wataru': 'Wataru End≈ç',
    'ezri konsa ngoyo': 'Ezri Konsa',
    'fabio ferreira vieira': 'F√°bio Vieira',
    'fabio freitas gouveia carvalho': 'Fabio Carvalho',
    'fabio henrique tavares': 'Fabinho',
    'fabricio agosto ramirez': 'Fabricio',
    'facundo pellistri rebollo': 'Facundo Pellistri',
    'faustino anjorin': 'Tino Anjorin',
    'felipe anderson pereira gomes': 'Felipe Anderson',
    'felipe augusto de almeida monteiro': 'Felipe Monteiro',
    'felipe rodrigues da silva': 'Morato',
    'fernando luiz rosa': 'Fernandinho',
    'fernando marcal': 'Mar√ßal',
    'filip benkovic': 'Filip Benkoviƒá',
    'filip marschall': 'Filip Marshall',
    'fin stevens': 'Finley Stevens',
    'florian lejeune': 'Florian Lejeune',
    'francisco casilla cortes': 'Kiko Casilla',
    'francisco evanilson de lima barbosa': 'Evanilson',
    'francisco femenia far': 'Kiko Femen√≠a',
    'francisco jorge tomas oliveira': 'Chiquinho',
    'francisco machado mota de castro trincao': 'Trinc√£o',
    'franco umeh-chibueze': 'Franco Umeh',
    'frederico rodrigues de paula santos': 'Fred',
    'frederik alves': 'Frederik Alves Ibsen',
    'gabriel dos santos magalhaes': 'Gabriel Magalh√£es',
    'gabriel fernando de jesus': 'Gabriel Jesus',
    'gabriel martinelli silva': 'Gabriel Martinelli',
    'gabriel teodoro martinelli silva': 'Gabriel Martinelli',
    'gedson carvalho fernandes': 'Gedson Fernandes',
    'giovanni reyna': 'Gio Reyna',
    'glenn murray': 'Glenn Murray',
    'goncalo manuel ganchinho guedes': 'Gon√ßalo Guedes',
    'gustavo henrique furtado scarpa': 'Gustavo Scarpa',
    'hector junior firpo adames': 'Junior Firpo',
    'helder wander sousa de azevedo e costa': 'H√©lder Costa',
    'henri lansbury': 'Henri Lansbury',
    'hugo bueno lopez': 'Hugo Bueno',
    'hwang hee-chan': 'Hee-chan Hwang',
    'hwang ui-jo': 'Ui-jo Hwang',
    'ian carlo poveda-ocampo': 'Ian Poveda',
    'igor julio dos santos de paulo': 'Igor',
    'illia zabarnyi': 'Ilya Zabarnyi',
    'indiana vassilev': 'Indiana Vassilev',
    'isaac success ajayi': 'Isaac Success',
    'ivan neves abreu cavaleiro': 'Ivan Cavaleiro',
    'ivan ricardo neves abreu cavaleiro': 'Ivan Cavaleiro',
    'jack wilshere': 'Jack Wilshere',
    'jaden philogene-bidace': 'Jaden Philogene',
    'javier manquillo': 'Manquillo',
    'javier manquillo gaitan': 'Manquillo',
    'jean-ricner bellegarde': 'Jean Bellegarde',
    'jefferson lerma solis': 'Jefferson Lerma',
    'jens cajuste': 'Jens-Lys Cajuste',
    'jeremy sarmiento morante': 'Jeremy Sarmiento',
    'joao cavaco cancelo': 'Jo√£o Cancelo',
    'joao felix sequeira': 'Jo√£o F√©lix',
    'joao filipe iria santos moutinho': 'Jo√£o Moutinho',
    'joao neves virginia': 'Jo√£o Virg√≠nia',
    'joao palhinha goncalves': 'Jo√£o Palhinha',
    'joao pedro cavaco cancelo': 'Jo√£o Cancelo',
    'joao pedro ferreira silva': 'Jota Silva',
    'joao pedro junqueira de jesus': 'Jo√£o Pedro',
    'joao victor gomes da silva': 'Jo√£o Gomes',
    'joe ayodele-aribo': 'Joe Aribo',
    'joelinton cassio apolinario de lira': 'Joelinton',
    'johann berg gudmundsson': 'J√≥hann Gu√∞mundsson',
    'jonathan castro otto': 'Jonny',
    'jorge cuenca barreno': 'Jorge Cuenca',
    'jorge luiz frello filho': 'Jorginho',
    'jose diogo dalot teixeira': 'Diogo Dalot',
    'jose ignacio peleteiro romallo': 'Jota Peleteiro',
    'jose malheiro de sa': 'Jos√© S√°',
    'joseph gomez': 'Joe Gomez',
    'joseph hodge': 'Joe Hodge',
    'joseph mcglynn': 'Joe McGlynn',
    'joseph whitworth': 'Joe Whitworth',
    'joseph willock': 'Joe Willock',
    'josh brooking': 'Joshua Brooking',
    'josh dasilva': 'Joshua Dasilva',
    'josh king': 'Joshua King',
    'josh martin': 'Josh Martin',
    'joshua sargent': 'Josh Sargent',
    'joshua wilson-esbrand': 'Josh Wilson-Esbrand',
    'juan camilo hernandez suarez': 'Cucho Hern√°ndez',
    'juan foyth': 'Juan Foyth',
    'juan larios lopez': 'Juan Larios',
    'julian araujo zuniga': 'Juli√°n Araujo',
    'junior firpo adames': 'Junior Firpo',
    'kaine hayden': 'Kaine Kesler-Hayden',
    'kaine kesler hayden': 'Kaine Kesler-Hayden',
    'kayky da silva chagas': 'Kayky',
    'kell watts': 'Kell Watts',
    'kelland watts': 'Kell Watts',
    'kepa arrizabalaga': 'Kepa',
    'kim ji-soo': 'Ji-soo Kim',
    'konstantinos tsimikas': 'Kostas Tsimikas',
    'leo fuhr hjelde': 'Leo Hjelde',
    'leonardo campana': 'Leonardo Campana',
    'lino da cruz sousa': 'Lino Sousa',
    'lucas rodrigues moura da silva': 'Lucas Moura',
    'lucas tolentino coelho de lima': 'Lucas Paquet√°',
    'lucas torreira': 'Lucas Torreira',
    'lucas torreira di pascua': 'Lucas Torreira',
    'luis guilherme lira dos santos': 'Luis Guilherme',
    'luis sinisterra lucumi': 'Luis Sinisterra',
    'luke mbete-tabu': 'Luke Mbete',
    'lyanco evangelista silveira neves vojnovic': 'Lyanco',
    'lyanco silveira neves vojnovic': 'Lyanco',
    'mads bech sorensen': 'Mads Bech',
    'mads juel andersen': 'Mads Andersen',
    'mads roerslev rasmussen': 'Mads Roerslev',
    'mahmoud ahmed ibrahim hassan': 'Tr√©z√©guet',
    'manuel benson hedilazio': 'Manuel Benson',
    'marc cucurella': 'Cucurella',
    'marc cucurella saseta': 'Cucurella',
    'marc guiu paz': 'Marc Guiu',
    'marc jurado gomez': 'Marc Jurado',
    'marc roca junque': 'Marc Roca',
    'marcelo de araujo pitaluga filho': 'Marcelo',
    'marcus myers-harness': 'Marcus Harness',
    'marcus oliveira alencar': 'Marquinhos Oliveira',
    'martin montoya': 'Mart√≠n Montoya',
    'mateo joseph fernandez': 'Mateo Joseph',
    'mateus cardoso lemos martins': 'Tet√™',
    'mateus goncalo espanha fernandes': 'Mateus Fernandes',
    'matheus franca de oliveira': 'Matheus Fran√ßa',
    'matheus luiz nunes': 'Matheus Nunes',
    'matheus santos carneiro da cunha': 'Matheus Cunha',
    'mathias jorgensen': 'Zanka',
    'matt phillips': 'Matthew Phillips',
    'matteo guendouzi': 'Matt√©o Guendouzi',
    'matthew cash': 'Matty Cash',
    'matthew smith': 'Matt Smith',
    'max kilman': 'Maximilian Kilman',
    'max kinsey': 'Maxwell Kinsey-Wellings',
    'max kinsey-wellings': 'Maxwell Kinsey-Wellings',
    'maximilian wober': 'Max W√∂ber',
    'maxwell haygarth': 'Max Haygarth',
    'mbwana ally samatta': 'Mbwana Samatta',
    'mbwana samatta': 'Mbwana Samatta',
    'mesut ozil': 'Mesut √ñzil',
    'michale olakigbe': 'Michael Olakigbe',
    'miguel almiron rejala': 'Miguel Almir√≥n',
    'mitoma kaoru': 'Kaoru Mitoma',
    'mohamed naser el sayed elneny': 'Mohamed Elneny',
    'mohamed salah': 'Mo Salah',
    'moises caicedo corozo': 'Mois√©s Caicedo',
    'murillo santiago costa dos santos': 'Murillo',
    'mykhailo mudryk': 'Mykhaylo Mudryk',
    'nathan wood-gordon': 'Nathan Wood',
    'nelson cabral semedo': 'N√©lson Semedo',
    'nicolas nkoulou': 'Nicolas N¬¥Koulou',
    'norberto bercique gomes betuncal': 'Beto',
    'norberto murara neto': 'Neto',
    'nuno varela tavares': 'Nuno Tavares',
    'odeluga offiah': 'Odel Offiah',
    'odysseas vlachodimos': 'Odisseas Vlachodimos',
    'oghenekaro peter etebo': 'Peter Etebo',
    'oliver arblaster': 'Ollie Arblaster',
    'olu aina': 'Ola Aina',
    'oluwasemilogo adesewo ibidapo ajayi': 'Semi Ajayi',
    'omari giraud-hutchinson': 'Omari Hutchinson',
    'oriol romeu vidal': 'Oriol Romeu',
    'orjan nyland': '√òrjan Nyland',
    'pablo fornals malla': 'Pablo Fornals',
    'pablo hernandez dominguez': 'Pablo Hern√°ndez',
    'pablo mari villar': 'Pablo Mar√≠',
    'pape matar sarr': 'Pape Sarr',
    'pedro cardoso de lima': 'Pedro Lima',
    'pedro lomba neto': 'Pedro Neto',
    'pelenda joshua dasilva': 'Joshua Dasilva',
    'pelly ruddock mpanzu': 'Pelly-Ruddock Mpanzu',
    'philippe coutinho correia': 'Philippe Coutinho',
    'raphael dias belloli': 'Raphinha',
    'rayan ait-nouri': 'Rayan A√Øt Nouri',
    'rekeem harper': 'Rakeem Harper',
    'renan augusto lodi dos santos': 'Renan Lodi',
    'renato palma veiga': 'Renato Veiga',
    'ricardo barbosa pereira': 'Ricardo Pereira',
    'ricardo domingos barbosa pereira': 'Ricardo Pereira',
    'richarlison de andrade': 'Richarlison',
    'robert elliot': 'Rob Elliot',
    'robert kenedy nunes do nascimento': 'Kenedy',
    'robert street': 'Rob Street',
    'roberto jimenez gago': 'Roberto',
    "rodrigo 'rodri' hernandez": 'Rodri',
    'rodrigo duarte ribeiro': 'Rodrigo Ribeiro',
    'rodrigo hernandez': 'Rodri',
    'rodrigo martins gomes': 'Rodrigo Gomes',
    'rodrigo moreno': 'Rodrigo',
    'rodrigo muniz carvalho': 'Rodrigo Muniz',
    'romelu lukaku bolingoli': 'Romelu Lukaku',
    'ruben da silva neves': 'R√∫ben Neves',
    'ruben diogo da silva neves': 'R√∫ben Neves',
    'ruben gato alves dias': 'R√∫ben Dias',
    'ruben goncalo silva nascimento vinagre': 'R√∫ben Vinagre',
    'ruben nascimento vinagre': 'R√∫ben Vinagre',
    'ruben santos gato alves dias': 'R√∫ben Dias',
    'rui pedro dos santos patricio': 'Rui Patr√≠cio',
    'runar alex runarsson': 'Alex R√∫narsson',
    'sam szmodics': 'Sammie Szmodics',
    'samir caetano de souza santos': 'Samir De Souza',
    'samuel amo-ameyaw': 'Sam Amo-Ameyaw',
    "savio 'savinho' moreira de oliveira": 'S√°vinho',
    'sergi canos tenes': 'Sergi Can√≥s',
    'sergio reguilon': 'Reguil√≥n',
    'sergio romero': 'Sergio Romero',
    'simon moore': 'Simon Moore',
    'sofiane boufal': 'Sofiane Boufal',
    'sokratis papastathopoulos': 'Sokratis Papastathopoulos',
    'solomon march': 'Solly March',
    'son heung-min': 'Heung-min Son',
    'stefan bajcetic maquieira': 'Stefan Bajƒçetiƒá',
    'stefan ortega moreno': 'Stefan Ortega',
    'sugawara yukinari': 'Yukinari Sugawara',
    'tanguy ndombele alvaro': 'Tanguy Ndomb√®l√©',
    'tariqe fosu-henry': 'Tariqe Fosu',
    'thakgalo leshabela': 'Khanya Leshabela',
    'thiago alcantara do nascimento': 'Thiago',
    'thiago emiliano da silva': 'Thiago Silva',
    'thiago thiago': 'Thiago Silva',
    'tom cannon': 'Thomas Cannon',
    'tom mcgill': 'Thomas McGill',
    'tomiyasu takehiro': 'Takehiro Tomiyasu',
    'toti antonio gomes': 'Toti',
    'treymaurice nyoni': 'Trey Nyoni',
    'troy parrott': 'Troy Parrott',
    'valentino livramento': 'Tino Livramento',
    'valintino adedokun': 'Valentin Adedokun',
    'vicente guaita': 'Guaita',
    'victor da silva': 'Vitinho',
    'vini de souza costa': 'Vinicius Souza',
    'vitalii mykolenko': 'Vitaliy Mykolenko',
    'vitor ferreira': 'Vitinha',
    'vontae daley-campbell': 'Vontae Campbell',
    'wanya marcal-madivadua': 'Wanya Mar√ßal',
    'wesley moraes': 'Wesley',
    'wesley moraes ferreira da silva': 'Wesley',
    'will lankshear': 'William Lankshear',
    'william fish': 'Will Fish',
    'william smallbone': 'Will Smallbone',
    'willian borges da silva': 'Willian',
    'willian jose da silva': 'Willian Jos√©',
    'winston reid': 'Winston Reid',
    'xande nascimento da costa silva': 'Xande Silva',
    'yago de santiago alonso': 'Yago Santiago',
    'yegor yarmoliuk': 'Yegor Yarmolyuk',
    'yehor yarmoliuk': 'Yegor Yarmolyuk',
    'yerson mosquera valdelamar': 'Yerson Mosquera',
    'yoshinori muto': 'Yoshinori Mut≈ç',
    'youssef ramalho chermiti': 'Youssef Chermiti',
    'yunus emre konak': 'Yunus Konak',
    'carlos ribeiro dias': 'cafu',
    'ben jackson': 'benjamin jackson',
    'aidan francis-clarke': 'aiden francis-clarke',
    'james storer': 'jimmy storer',
    'joel robles': 'joel',
    'kamari doyle': 'kami doyle'
}

In [15]:
from unidecode import unidecode

def normalize_name(name):
    return unidecode(name.strip().lower())

In [16]:
fts['name'] = fts['name'].apply(lambda x: normalize_name(x))
fts['name'] = fts['name'].apply(lambda x: normalize_name(name_map[x]) if x in name_map else x)
fts['name'].nunique()

1527

In [17]:
def create_time_category(df):
    df['play_time_category'] = df['minutes'].apply(lambda x: 1 if x > 45 else 0)
    return df

In [18]:
fts = create_time_category(fts)
fts.head()

,name,team,GW,season,total_points,bonus,value,creativity,influence,threat,selected,transfers_balance,minutes,kickoff_time,was_home,opponent_team,play_time_category
0,aaron connolly,Brighton,1,2020-2021,1,0,55,0.3,1.2,32.0,32205,0,45,2020-09-14T19:15:00Z,True,Chelsea,0
1,aaron cresswell,West Ham,1,2020-2021,1,0,50,11.2,10.4,0.0,70232,0,90,2020-09-12T19:00:00Z,True,Newcastle,1
2,aaron mooy,Brighton,1,2020-2021,0,0,50,0.0,0.0,0.0,2010,0,0,2020-09-14T19:15:00Z,True,Chelsea,0
3,aaron ramsdale,Sheffield Utd,1,2020-2021,1,0,50,0.0,18.2,0.0,462939,0,90,2020-09-14T17:00:00Z,True,Wolves,1
4,abdoulaye doucoure,Everton,1,2020-2021,3,0,55,44.6,20.4,4.0,143040,0,90,2020-09-13T15:30:00Z,False,Spurs,1

### Normalize

In [19]:
from sklearn.preprocessing import StandardScaler

features_need_scaling = ['total_points', 'bonus', 'value', 'creativity', 'influence', 'threat', 'selected', 'transfers_balance']

scaler = StandardScaler()
fts[features_need_scaling] = scaler.fit_transform(fts[features_need_scaling])
fts.head(10)

,name,team,GW,season,total_points,bonus,value,creativity,influence,threat,selected,transfers_balance,minutes,kickoff_time,was_home,opponent_team,play_time_category
0,aaron connolly,Brighton,1,2020-2021,-0.078159,-0.202513,0.448507,-0.379431,-0.410854,2.305655,-0.291139,-0.022899,45,2020-09-14T19:15:00Z,True,Chelsea,0
1,aaron cresswell,West Ham,1,2020-2021,-0.078159,-0.202513,0.014965,0.694707,0.344144,-0.368670,-0.227007,-0.022899,90,2020-09-12T19:00:00Z,True,Newcastle,1
2,aaron mooy,Brighton,1,2020-2021,-0.496432,-0.202513,0.014965,-0.408994,-0.509332,-0.368670,-0.342063,-0.022899,0,2020-09-14T19:15:00Z,True,Chelsea,0
3,aaron ramsdale,Sheffield Utd,1,2020-2021,-0.078159,-0.202513,0.014965,-0.408994,0.984251,-0.368670,0.435290,-0.022899,90,2020-09-14T17:00:00Z,True,Wolves,1
4,abdoulaye doucoure,Everton,1,2020-2021,0.758388,-0.202513,0.448507,3.986101,1.164794,-0.034380,-0.104217,-0.022899,90,2020-09-13T15:30:00Z,False,Spurs,1
5,aboubakar kamara,Fulham,1,2020-2021,0.340115,-0.202513,0.014965,-0.231613,-0.509332,0.049193,-0.334135,-0.022899,62,2020-09-12T11:30:00Z,True,Arsenal,1
6,adama traore,Wolves,1,2020-2021,0.758388,-0.202513,1.315590,-0.231613,0.541100,1.052065,1.659945,-0.022899,90,2020-09-14T17:00:00Z,False,Sheffield Utd,1
7,adam forshaw,Leeds,1,2020-2021,-0.496432,-0.202513,0.014965,-0.408994,-0.509332,-0.368670,-0.342065,-0.022899,0,2020-09-12T16:30:00Z,False,Liverpool,0
8,adam lallana,Brighton,1,2020-2021,-0.078159,-0.202513,1.315590,2.271423,0.048710,-0.201525,-0.212798,-0.022899,44,2020-09-14T19:15:00Z,True,Chelsea,0
9,adam webster,Brighton,1,2020-2021,-0.078159,-0.202513,-0.418577,0.753834,0.705230,-0.285098,-0.029328,-0.022899,90,2020-09-14T19:15:00Z,True,Chelsea,1

In [20]:
fts['creativity'].describe()

count    1.060420e+05
mean     7.075811e-17
std      1.000005e+00
min     -4.089939e-01
25%     -4.089939e-01
50%     -4.089939e-01
75%     -2.611768e-01
max      1.301280e+01
Name: creativity, dtype: float64

### Create form

In [21]:

features = [col for col in features_need_scaling]

fts = fts.sort_values(['name', 'kickoff_time']).reset_index(drop=True)

# def get_form(df, features):
#     result = df.copy()
#     weights = [0.1, 0.2, 0.3, 0.4] 

#     for feature in features:
#         rolling_feature = (
#             df[df['minutes'] > 0]  
#             .groupby('name')[feature]
#             .apply(lambda x: x.shift(1)  
#                    .rolling(window=4, min_periods=1)  
#                    .apply(lambda y: sum(w * v for w, v in zip(weights[:len(y)], y)), raw=True))  
#             .reset_index(level=0, drop=True)
#         )
#         result[f'form_{feature}'] = rolling_feature.combine_first(df[feature])
    
#     return result


# fts = get_form(fts, features)

In [22]:
# fts.drop(columns=features, inplace=True)
# fts

In [23]:
fts[fts['name'] == 'marcus rashford']

,name,team,GW,season,total_points,bonus,value,creativity,influence,threat,selected,transfers_balance,minutes,kickoff_time,was_home,opponent_team,play_time_category
67961,marcus rashford,Man Utd,2,2020-2021,0.340115,-0.202513,3.916841,2.675456,0.163601,0.467056,0.406707,1.522296,90,2020-09-19T16:30:00Z,True,Crystal Palace,1
67962,marcus rashford,Man Utd,3,2020-2021,2.431482,-0.202513,3.916841,1.019905,2.494247,2.890664,0.296542,-1.013171,90,2020-09-26T11:30:00Z,False,Brighton,1
67963,marcus rashford,Man Utd,4,2020-2021,0.340115,-0.202513,3.916841,1.059323,-0.049768,-0.201525,0.405403,0.623614,90,2020-10-04T15:30:00Z,True,Spurs,1
67964,marcus rashford,Man Utd,5,2020-2021,5.777669,4.195371,3.916841,3.118908,5.776847,8.907896,0.358585,-0.609223,90,2020-10-17T19:00:00Z,False,Newcastle,1
67965,marcus rashford,Man Utd,6,2020-2021,0.340115,-0.202513,3.916841,1.443647,0.114362,2.639946,0.520108,1.122072,90,2020-10-24T16:30:00Z,True,Chelsea,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68108,marcus rashford,Man Utd,35,2023-2024,-0.496432,-0.202513,2.963049,-0.408994,-0.509332,-0.368670,1.460803,-0.336253,0,2024-04-27T14:00:00Z,True,Burnley,0
68109,marcus rashford,Man Utd,36,2023-2024,-0.496432,-0.202513,2.963049,-0.408994,-0.509332,-0.368670,1.434915,-0.241425,0,2024-05-06T19:00:00Z,False,Crystal Palace,0
68110,marcus rashford,Man Utd,37,2023-2024,-0.496432,-0.202513,2.963049,-0.408994,-0.509332,-0.368670,1.414021,-0.193789,0,2024-05-12T15:30:00Z,True,Arsenal,0
68111,marcus rashford,Man Utd,37,2023-2024,-0.078159,-0.202513,2.963049,-0.369576,-0.312376,0.049193,1.414021,-0.193789,7,2024-05-15T19:00:00Z,True,Newcastle,0
68112,marcus rashford,Man Utd,38,2023-2024,-0.078159,-0.202513,2.963049,-0.349867,-0.213898,-0.368670,1.408478,-0.078810,15,2024-05-19T15:00:00Z,False,Brighton,0

In [24]:
fts.drop(columns=['minutes', 'kickoff_time'], inplace=True)

In [25]:
# check if there is any team name in fts that is not in the value of the map
fts['team'].unique()

array(['Brighton', 'West Ham', 'Brentford', 'Burnley', 'Sheffield Utd',
       'Arsenal', 'Aston Villa', 'Man Utd', 'Everton', 'Chelsea',
       'Fulham', 'Norwich', 'Southampton', 'Leeds', 'Watford',
       'Bournemouth', 'Crystal Palace', 'Wolves', 'Leicester', 'Luton',
       'Liverpool', 'Man City', 'West Brom', 'Spurs', 'Newcastle',
       "Nott'm Forest"], dtype=object)

In [26]:
team_name_map = {
    'Arsenal' : 'ARS',
    'Aston Villa': 'AVL',
    'Bournemouth': 'BOU',
    'Brentford': 'BRE',
    'Brighton': 'BHA',
    'Burnley': 'BUR',
    'Chelsea': 'CHE',
    'Crystal Palace': 'CRY',
    'Everton': 'EVE',
    'Fulham': 'FUL',
    'Ipswich': 'IPS',
    'Leicester': 'LEI',
    'Liverpool' : 'LIV',
    'Luton': 'LUT',
    'Man City': 'MCI',
    'Man Utd': 'MUN',
    'Newcastle': 'NEW',
    'Nott\'m Forest': 'NFO',
    'Sheffield Utd': 'SHU',
    'Spurs': 'TOT',
    'West Ham': 'WHU',
    'Wolves': 'WOL',
    'Leeds': 'LEE',
    'Norwich': 'NOR',
    'Watford': 'WAT',
    'West Brom': 'WBA',
    'Cardiff': 'CAR',
    'Southampton': 'SOU'
}

In [27]:
set(fts['team'].unique()) - set(team_name_map.keys())

set()

In [28]:
fts.rename(columns={'GW': 'round'}, inplace=True)

In [29]:
fts['team'] = fts['team'].apply(lambda x: team_name_map[x])
fts.head(10)

,name,team,round,season,total_points,bonus,value,creativity,influence,threat,selected,transfers_balance,was_home,opponent_team,play_time_category
0,aaron connolly,BHA,1,2020-2021,-0.078159,-0.202513,0.448507,-0.379431,-0.410854,2.305655,-0.291139,-0.022899,True,Chelsea,0
1,aaron connolly,BHA,2,2020-2021,2.849755,4.195371,0.448507,0.704562,2.346530,1.553501,-0.286375,-0.038966,False,Newcastle,1
2,aaron connolly,BHA,3,2020-2021,0.340115,-0.202513,0.448507,0.783397,-0.509332,0.299911,-0.252095,0.164294,True,Man Utd,1
3,aaron connolly,BHA,4,2020-2021,0.340115,-0.202513,0.448507,-0.379431,-0.263137,-0.034380,-0.252485,-0.041042,False,Everton,1
4,aaron connolly,BHA,5,2020-2021,1.176662,-0.202513,0.448507,0.606017,0.902186,-0.201525,-0.266569,-0.147344,False,Crystal Palace,0
5,aaron connolly,BHA,6,2020-2021,-0.496432,-0.202513,0.448507,-0.408994,-0.509332,-0.368670,-0.259749,0.005514,True,West Brom,0
6,aaron connolly,BHA,7,2020-2021,-0.496432,-0.202513,0.448507,-0.408994,-0.509332,-0.368670,-0.272011,-0.120398,False,Spurs,0
7,aaron connolly,BHA,8,2020-2021,-0.078159,-0.202513,0.361799,-0.408994,-0.492919,-0.368670,-0.278317,-0.080194,True,Burnley,0
8,aaron connolly,BHA,9,2020-2021,-0.496432,-0.202513,0.361799,-0.408994,-0.509332,-0.368670,-0.289009,-0.106711,False,Aston Villa,0
9,aaron connolly,BHA,10,2020-2021,0.340115,-0.202513,0.275090,0.773543,-0.509332,2.054937,-0.291890,-0.055491,True,Liverpool,1

### Players Name

In [30]:
player_info = pd.read_csv('../../data/raw/worldfb/worldfb_players.csv')
player_info

          Season  Round          Team             Player Name  Is Home
0      2019-2020      1  Liverpool FC          Alisson Becker        1
1      2019-2020      1  Liverpool FC         Virgil van Dijk        1
2      2019-2020      1  Liverpool FC               Joe Gomez        1
3      2019-2020      1  Liverpool FC          Andy Robertson        1
4      2019-2020      1  Liverpool FC  Trent Alexander-Arnold        1
...          ...    ...           ...                     ...      ...
78593  2024-2025     11    Arsenal FC            Jakub Kiwior        0
78594  2024-2025     11    Arsenal FC     Oleksandr Zinchenko        0
78595  2024-2025     11    Arsenal FC                Jorginho        0
78596  2024-2025     11    Arsenal FC      Myles Lewis-Skelly        0
78597  2024-2025     11    Arsenal FC           Ethan Nwaneri        0

[78598 rows x 5 columns]

In [31]:
mapping = {
    'Fulham FC': 'FUL',
    'Arsenal FC': 'ARS',
    'Crystal Palace': 'CRY',
    'Southampton FC': 'SOU',
    'Liverpool FC': 'LIV',
    'Leeds United': 'LEE',
    'West Ham United': 'WHU',
    'Newcastle United': 'NEW',
    'West Bromwich Albion': 'WBA',
    'Leicester City': 'LEI',
    'Tottenham Hotspur': 'TOT',
    'Everton FC': 'EVE',
    'Sheffield United': 'SHU',
    'Wolverhampton Wanderers': 'WOL',
    'Brighton & Hove Albion': 'BHA',
    'Chelsea FC': 'CHE',
    'Burnley FC': 'BUR',
    'Manchester United': 'MUN',
    'Manchester City': 'MCI',
    'Aston Villa': 'AVL',
    'Brentford FC': 'BRE',
    'Watford FC': 'WAT',
    'Norwich City': 'NOR',
    'AFC Bournemouth': 'BOU',
    'Nottingham Forest': 'NFO',
    'Luton Town': 'LUT',
    'Ipswich Town': 'IPS'
}

player_info['Team'] = player_info['Team'].apply(lambda x: mapping[x] if x in mapping else x)

player_info['Team'].unique()

array(['LIV', 'NOR', 'WHU', 'MCI', 'BOU', 'SHU', 'BUR', 'SOU', 'CRY',
       'EVE', 'WAT', 'BHA', 'TOT', 'AVL', 'LEI', 'WOL', 'NEW', 'ARS',
       'MUN', 'CHE', 'FUL', 'LEE', 'WBA', 'BRE', 'NFO', 'LUT', 'IPS'],
      dtype=object)

In [32]:
player_info = player_info[player_info['Season'].isin(['2020-2021', '2021-2022', '2022-2023', '2023-2024', '2024-2025'])]

In [33]:
# # get the team for each player in diff
# diff = set(fts['name'].unique()) - set(player_info['Player Name'].unique())
# diff_map = fts[['name', 'team']].drop_duplicates()
# diff_map = diff_map[diff_map['name'].isin(diff)]
# diff_map

In [34]:
player_info['Player Name'] = player_info['Player Name'].apply(lambda x: normalize_name(x))
player_info['Player Name'].nunique()

/var/folders/gd/ntbln7kx6cdfjdyfkm0ynzt40000gn/T/ipykernel_34385/2686757649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  player_info['Player Name'] = player_info['Player Name'].apply(lambda x: normalize_name(x))

1514

In [35]:
fts_redundant = set(fts['name'].unique()) - set(player_info['Player Name'].unique())
fts_redundant

{'aaron mooy',
 'abdul rahman baba',
 'adedapo awokoya-mebude',
 'admiral muskwe',
 'adrien silva',
 'albian ajeti',
 'alfie mawson',
 'andre gray',
 'angelo gabriel borges damaceno',
 'aribim pepple',
 'barry douglas',
 'ben wilmot',
 'bendeguz bolla',
 'braian ojeda rodriguez',
 'brandon pierrick',
 'brice samba',
 'bruno borges fernandes',
 'bruno cavaco jordao',
 'cameron carter-vickers',
 'carlos mendes gomes',
 'chris smalling',
 'christian atsu',
 'claudio bravo',
 'darko churlinov',
 'denis franchi',
 'dion pereira',
 'domingos quina',
 'enock agyei',
 'ethan wady',
 'filip benkovic',
 'florian lejeune',
 'gabriel slonina',
 'garang kuol',
 'glen rea',
 'glenn murray',
 'harry arter',
 'henri lansbury',
 'indiana vassilev',
 'isaac success',
 'jack walton',
 'jack wilshere',
 'jackson smith',
 'jan zamburek',
 'jaroslaw jach',
 'jay-roy grot',
 'jean michael seri',
 'joe lolley',
 'joe taylor',
 'jonathan leko',
 'jonathan panzo',
 'jordan hugill',
 'jordan stevens',
 'joseph hungbo',
 'josh bowler',
 'josh martin',
 'josh powell',
 'josh sims',
 'jota peleteiro',
 'juan foyth',
 'kacper kozlowski',
 'kamil miazek',
 'kell watts',
 'kenneth zohore',
 'kevin mcdonald',
 'leo bonatini',
 'leonardo campana',
 'louie watson',
 'lucas torreira',
 'luke freeman',
 'luke mcnally',
 'marc navarro',
 'marco stiepermann',
 'marcos rojo',
 'martin montoya',
 'mateusz lis',
 'matt clarke',
 'matteo guendouzi',
 'matthew clarke',
 'matthew pollock',
 'matty james',
 'mbwana samatta',
 'mesut ozil',
 'mohamed drager',
 'omar richards',
 'onel hernandez',
 'orjan nyland',
 'paulo gazzaniga',
 'paulo gazzaniga farias',
 'philip zinckernagel',
 'richie laryea',
 'roberto',
 'rolando aarons',
 'ryan bennett',
 'samuel bastien',
 'scott twine',
 'sergio romero',
 'simon moore',
 'sofiane boufal',
 'sokratis papastathopoulos',
 'stipe perica',
 'tom dele-bashiru',
 'troy parrott',
 'winston reid',
 'xande silva',
 'yoshinori muto',
 'zach awe',
 'zeze steven sessegnon'}

In [36]:
fts = fts[~fts['name'].isin(fts_redundant)]
fts['name'].nunique()

1420

In [37]:
player_info_redundant = set(player_info['Player Name'].unique()) - set(fts['name'].unique())
# remove row where player name is in player_info_redundant
player_info = player_info[~player_info['Player Name'].isin(player_info_redundant)]
player_info

          Season  Round Team          Player Name  Is Home
14034  2020-2021      1  FUL          marek rodak        1
14035  2020-2021      1  FUL       michael hector        1
14036  2020-2021      1  FUL           denis odoi        1
14037  2020-2021      1  FUL             tim ream        1
14038  2020-2021      1  FUL            joe bryan        1
...          ...    ...  ...                  ...      ...
78593  2024-2025     11  ARS         jakub kiwior        0
78594  2024-2025     11  ARS  oleksandr zinchenko        0
78595  2024-2025     11  ARS             jorginho        0
78596  2024-2025     11  ARS   myles lewis-skelly        0
78597  2024-2025     11  ARS        ethan nwaneri        0

[63945 rows x 5 columns]

In [38]:
player_info[player_info['Player Name'] == 'cristiano ronaldo']

          Season  Round Team        Player Name  Is Home
30043  2021-2022      4  MUN  cristiano ronaldo        1
30623  2021-2022      5  MUN  cristiano ronaldo        0
30723  2021-2022      6  MUN  cristiano ronaldo        1
31086  2021-2022      7  MUN  cristiano ronaldo        1
31581  2021-2022      8  MUN  cristiano ronaldo        0
32240  2021-2022      9  MUN  cristiano ronaldo        1
32541  2021-2022     10  MUN  cristiano ronaldo        0
32721  2021-2022     11  MUN  cristiano ronaldo        1
33300  2021-2022     12  MUN  cristiano ronaldo        0
33823  2021-2022     13  MUN  cristiano ronaldo        0
34237  2021-2022     14  MUN  cristiano ronaldo        1
34517  2021-2022     15  MUN  cristiano ronaldo        1
34897  2021-2022     16  MUN  cristiano ronaldo        0
35413  2021-2022     17  MUN  cristiano ronaldo        0
35709  2021-2022     18  MUN  cristiano ronaldo        1
36124  2021-2022     19  MUN  cristiano ronaldo        0
36497  2021-2022     20  MUN  cristiano ronaldo        1
36934  2021-2022     21  MUN  cristiano ronaldo        1
37613  2021-2022     23  MUN  cristiano ronaldo        1
37997  2021-2022     24  MUN  cristiano ronaldo        0
38251  2021-2022     25  MUN  cristiano ronaldo        1
38992  2021-2022     26  MUN  cristiano ronaldo        0
39212  2021-2022     27  MUN  cristiano ronaldo        1
39931  2021-2022     29  MUN  cristiano ronaldo        1
41110  2021-2022     32  MUN  cristiano ronaldo        0
41570  2021-2022     33  MUN  cristiano ronaldo        1
41870  2021-2022     34  MUN  cristiano ronaldo        0
42610  2021-2022     35  MUN  cristiano ronaldo        1
42830  2021-2022     36  MUN  cristiano ronaldo        0
43049  2021-2022     37  MUN  cristiano ronaldo        1
44172  2022-2023      1  MUN  cristiano ronaldo        1
44507  2022-2023      2  MUN  cristiano ronaldo        0
45012  2022-2023      3  MUN  cristiano ronaldo        1
45071  2022-2023      4  MUN  cristiano ronaldo        0
45831  2022-2023      5  MUN  cristiano ronaldo        0
46211  2022-2023      6  MUN  cristiano ronaldo        1
47355  2022-2023      9  MUN  cristiano ronaldo        0
47789  2022-2023     10  MUN  cristiano ronaldo        0
48164  2022-2023     11  MUN  cristiano ronaldo        1
48494  2022-2023     12  MUN  cristiano ronaldo        1
49404  2022-2023     14  MUN  cristiano ronaldo        1
49704  2022-2023     15  MUN  cristiano ronaldo        0

In [39]:
player_info.to_csv('../../data/preprocessed/info/player_info.csv', index=False)

In [40]:
fts['opponent_team'] = fts['opponent_team'].apply(lambda x: team_name_map[x])

In [41]:
# create home_1, away_1, home_0, away_0
fts_home_1 = fts[(fts['was_home'] == True) & (fts['play_time_category'] == 1)]
fts_away_1 = fts[(fts['was_home'] == False) & (fts['play_time_category'] == 1)]
fts_home_0 = fts[(fts['was_home'] == True) & (fts['play_time_category'] == 0)]
fts_away_0 = fts[(fts['was_home'] == False) & (fts['play_time_category'] == 0)]

In [42]:
fts_home_0.to_csv('../../data/preprocessed/layer2/fts_home_0.csv', index=False)
fts_home_1.to_csv('../../data/preprocessed/layer2/fts_home_1.csv', index=False)
fts_away_0.to_csv('../../data/preprocessed/layer2/fts_away_0.csv', index=False)
fts_away_1.to_csv('../../data/preprocessed/layer2/fts_away_1.csv', index=False)

In [43]:
matches_info = pd.read_csv('../../data/raw/worldfb/worldfb_matches.csv')
matches_info.head()

,Match ID,Season,Round,Home Team,Away Team,Home Coach,Away Coach
0,2019-2020_1,2019-2020,1,Liverpool FC,Norwich City,J√ºrgen Klopp,Daniel Farke
1,2019-2020_2,2019-2020,1,West Ham United,Manchester City,Manuel Pellegrini,Pep Guardiola
2,2019-2020_3,2019-2020,1,AFC Bournemouth,Sheffield United,Eddie Howe,Chris Wilder
3,2019-2020_4,2019-2020,1,Burnley FC,Southampton FC,Sean Dyche,Ralph Hasenh√ºttl
4,2019-2020_5,2019-2020,1,Crystal Palace,Everton FC,Roy Hodgson,Marco Silva

In [44]:
matches_info['Home Team'] = matches_info['Home Team'].apply(lambda x: mapping[x] if x in mapping else x)
matches_info['Away Team'] = matches_info['Away Team'].apply(lambda x: mapping[x] if x in mapping else x)
matches_info['Home Coach'] = matches_info['Home Coach'].apply(lambda x: normalize_name(x))
matches_info['Away Coach'] = matches_info['Away Coach'].apply(lambda x: normalize_name(x))
matches_info

,Match ID,Season,Round,Home Team,Away Team,Home Coach,Away Coach
0,2019-2020_1,2019-2020,1,LIV,NOR,jurgen klopp,daniel farke
1,2019-2020_2,2019-2020,1,WHU,MCI,manuel pellegrini,pep guardiola
2,2019-2020_3,2019-2020,1,BOU,SHU,eddie howe,chris wilder
3,2019-2020_4,2019-2020,1,BUR,SOU,sean dyche,ralph hasenhuttl
4,2019-2020_5,2019-2020,1,CRY,EVE,roy hodgson,marco silva
...,...,...,...,...,...,...,...
2005,2024-2025_2006,2024-2025,11,LIV,AVL,arne slot,unai emery
2006,2024-2025_2007,2024-2025,11,MUN,LEI,ruud van nistelrooy,steve cooper
2007,2024-2025_2008,2024-2025,11,NFO,NEW,nuno espirito santo,eddie howe
2008,2024-2025_2009,2024-2025,11,TOT,IPS,ange postecoglou,kieran mckenna
2009,2024-2025_2010,2024-2025,11,CHE,ARS,enzo maresca,mikel arteta

In [45]:
matches_info = matches_info[matches_info['Season'].isin(['2020-2021', '2021-2022', '2022-2023', '2023-2024', '2024-2025'])]
matches_info

,Match ID,Season,Round,Home Team,Away Team,Home Coach,Away Coach
380,2020-2021_381,2020-2021,1,FUL,ARS,scott parker,mikel arteta
381,2020-2021_382,2020-2021,1,CRY,SOU,roy hodgson,ralph hasenhuttl
382,2020-2021_383,2020-2021,1,LIV,LEE,jurgen klopp,marcelo bielsa
383,2020-2021_384,2020-2021,1,WHU,NEW,david moyes,steve bruce
384,2020-2021_385,2020-2021,1,WBA,LEI,slaven bilic,brendan rodgers
...,...,...,...,...,...,...,...
2005,2024-2025_2006,2024-2025,11,LIV,AVL,arne slot,unai emery
2006,2024-2025_2007,2024-2025,11,MUN,LEI,ruud van nistelrooy,steve cooper
2007,2024-2025_2008,2024-2025,11,NFO,NEW,nuno espirito santo,eddie howe
2008,2024-2025_2009,2024-2025,11,TOT,IPS,ange postecoglou,kieran mckenna
2009,2024-2025_2010,2024-2025,11,CHE,ARS,enzo maresca,mikel arteta

In [46]:
# matches_info.to_csv('../../data/preprocessed/info/matches_info.csv', index=False)